### ISSUE TITLE
Ambassador

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#35]
This role is responsible for representing Bisq online and in the physical world whenever and wherever it is useful to do so. Ambassador work ranges from answering questions about Bisq on Reddit to giving talks about Bisq at conferences and anything in between.

This is ideally a role that will be filled by many people, not just one or two, but we'll get there over time. Note that certain extra-important outreach channels like Twitter have their own infrastructure and dedicated roles—see #21 for an example of that.

Slack: `#ambassadors`

----

Docs: none, other than above
Team: none, role is open to all
Primary owner: none, see https://github.com/bisq-network/roles/issues/35#issuecomment-402209182

**Comment by cbeams** [comment]
## 2017.12 report

_From this point forward, I'll start reporting here in the Ambassador role about whatever outreach activities / interviews, etc I've done over the prior month. Other ambassadors should do the same, with regard to talks they've given, work they've done on various social media platforms, meetups, etc. Note that the details below do not include my work running the @bisq_network twitter handle, which is tracked on its own at #21._

 - December Bitcoin Austria meetup, where I did a lot of Q&A during the networking session after the main presentation: https://twitter.com/cbeams/status/940638403296624641

 - WCN Bitcoin News Show on Decentralized Exchanges (12K views): https://www.youtube.com/watch?v=VoSLBsUsmTo

 - Talk on Bisq at 34C3 in Leipzig
   - Was given to a packed audience, approx 75–100 people
   - Announcement tweet: https://twitter.com/bisq_network/status/946350521518043137
   - Slides: https://goo.gl/h4CJuo
   - Video soon: https://twitter.com/bisq_network/status/948144443785469952

/cc bisq-network/compensation#26

**Comment by cbeams** [comment]
## 2018.01 report

 - Podcast interview with the Steal This Show podcast on Bisq (https://github.com/bisq-network/events/issues/10)
 - Written interview with ForkLog on recent Coincheck hack (https://github.com/bisq-network/events/issues/11)

/cc bisq-network/compensation#35

**Comment by cbeams** [comment]
## 2018.02 report

As it turns out the Steal this Show and ForkLog interviews mentioned above did not actually come out in January, they came out this month, so I'm mentioning them here again for completeness. In the spirit of including only complete, finished, shipped work in compensation requests, I won't mention future such interviews in a monthly report until they've actually become publicly available.

What follows is copied from this month's update for Events Maintainer at https://github.com/bisq-network/roles/issues/65#issuecomment-369394950

> - Part I of @cbeams' podcast interview with Steal This Show dropped this month: https://github.com/bisq-network/events/issues/10
>  - @cbeams' written interview with Forklog came out: https://github.com/bisq-network/events/issues/11
>  - @cbeams' written interview with Bitcoin Magazine came out: https://github.com/bisq-network/events/issues/14
> 
> > _NOTE: I'm still not sure where the best repo/board for these issues is. They're not quite "events", and we don't have a repo for "ambassador" issues. Maybe we should. In the meantime, I'll duplicate the above entries in my report this month on the Ambassador role (#35)._

There is other ambassador work that went on throughout the month as well, including @flix1 posting on Reddit, @alexej996 doing BitcoinTalk updates and more, but I'll let them weigh in here with their own comments in the future. Anyone playing the role of Ambassador should do this, if they want to keep folks up to date about their efforts & to include them in compensation requests. Doesn't need to be lengthy, but would be great to have summaries of what people are doing and how they think those efforts are going.

/cc bisq-network/compensation#40

**Comment by cbeams** [comment]
## 2018.03 report

 - I did an interview with Zack Voell on the Coin Pod that came out on March 21st, see https://github.com/bisq-network/events/issues/19.
 - I did an interview with JW Weatherman on Under the Microscope that streamed live on on March 24th, see https://github.com/bisq-network/events/issues/20.

PLEASE NOTE: It would be great to see other Bisq ambassadors reporting here on the work that they are doing, and requesting compensation for it! I know not everyone is doing podcast interviews and the like, but any serious efforts you engage in to represent and promote Bisq are worth mentioning here.

/cc bisq-network/compensation#57

**Comment by cbeams** [comment]
## 2018.04 report

Nothing to report.

/cc bisq-network/compensation#68

**Comment by ManfredKarrer** [comment]
## 2018.06 report

I took over the primary role ownership that month.

I was in contact with a Vietnamese Bisq user who sponsored the translation work (he paid from his pocket for that, and wants to add more Asian translations) and tried to invite him to a future growth call. He rejected for privacy reasons but gave me some contacts, which I forwarded to @flix1.

/cc bisq-network/compensation#92

**Comment by cbeams** [comment]
## 2018.06 report

Nothing to report.

/cc bisq-network/compensation#89

**Comment by cbeams** [comment]
@ManfredKarrer wrote:

> I took over the primary role ownership this month.

Thanks, @ManfredKarrer and @meapistol for taking over primary and secondary ownership of this role from me. Here's the thing, though: I don't think this role needs owners at all.

The reason why this role doesn't need _owners_ is because there are no special _rights_ required to perform the _duties_ of an Ambassador.

From https://deploy-preview-46--bisq-docs.netlify.com/roles.html#properties:

![image](https://user-images.githubusercontent.com/301810/42231019-b92c491e-7eea-11e8-934d-1a3b2e7b9ead.png)

Basically, anyone can play this role, and no one strictly has to, so people should post reports here if they have something to say, but no one needs to "own" doing so. Ambassador stays in a perpetual "help wanted" state, but that's fine.

To this end, I've removed everyone as an assignee (including myself). Please give a thumbs up here if this all makes sense and works for you.

(The doc above is WIP at https://github.com/bisq-network/bisq-docs/pull/46 and nearly ready for review)

**Comment by ghost** [comment]
For information, concerning Reddit:
I gave an eye to reddit, and was happily surprised to see that Bisq is mentionned on average once/day on differents subreddits. 
Sometimes for bad reasons, sometimes under the form of questions.
So since ~22th of july, I monitor the r/bisq subreddit + reddit itself, ie I survey the occurrence of « bisq » everywhere, and try to help/inform/advertize when possible.
I try also to post something about Bisq everyday or every 2 days in the r/bisq

If it's ok for you, I'll do that as long as the returns are good.

edit: atm, each post on /r/bisq makes ~100 views after ~1week, is 100% upvoted (by ~10% of the views)

**Comment by ghost** [comment]
##  2018.07 Report

### Reddit
Reddit (as a whole, not just /r/bisq), and **exclusively the last week of July**.
Spending some time on the /r/bisq subreddit, I constated that :
- there are always a (variable) bunch of people reading, whatever the hour
- there are days, rows of days, where nothing is posted on the subreddit.

By coincidence I also felt on this worth viewing 5’ video : Why YouTube Comments Suck (and Reddit comments don't) https://youtu.be/Lvf8koqX_yE
Being in the Bisq boat since mid-may, it seems me that :
- given the vitality of the project dev itself,
- the already existing quantity of informational material,
- the general cryptoworld news, 
- the trends in the bisq markets (needs some markets following to help reinforcement effect)

There should be enough material in order to post something interesting and useful everyday or every 2 days. 
I also noticed that the ambassador role : https://github.com/bisq-network/roles/issues/35 is still tagged `help wanted`.
So I decided to give a try to reddit.
The returns are (as measured with reddit’s metrics : views, upvote) quite good. For the moment I have no precise idea on the impact outside the reddit sphere, but given that there is a willing audience, I think it’s worth to use this subreddit and other subreddits for Bisq’s promotion and it’s also good to transmit and reflect Bisq’s vitality there.
Imo the future of Bisq (if not killed before) is in the crypto/crypto market. Specialized and active crypto dedicated forum are (of course) a good place to try to push liquidity.
I’ll thus be very interested by suggestions on pertinent/fruitful subreddits to consider.
My activity summary : https://www.reddit.com/user/dieter_von_bisq/about/traffic/ (9 posts + 8 comments) 

atm I assume that everything publicly accessible concerning Bisq may be published on reddit.
If this is not the case for this or this information, please let me know.

### Mastodon
It’s a different story (and gives an interesting comparison).
I make a first try on the https://framapiaf.org instance.
Mastodon is a kind of twitter, but decentralized/federated. It’s however a young thing, with ~ 1 millions users (compared to twitter’s 300 millions).
Everything is to build from the very beginning there, but I feel it’s good that Bisq exists there.
Framapiaf is french language oriented, quite social, leftist, not bitcoin inclined. Although it’s open and technical, I feel that framapiaf is probably atm not the best instance for a Bisq account. 
The return atm narrows 0 at best.
I will prospect for a better instance in the future.

### Twister
I get a little look there, but this project/media seems alas stalled and not greatly used.

Since doing already the animation work for reddit, I may factorize on other places if wanted. Suggestions welcome.

**Comment by ghost** [comment]
## 2018.08 Report (Reddit)

I started the reddit animation on july 22th (see previous report)

Our own r/bisq subreddit is not very active, but this is slightly changing.
As of today, r/bisq has 749 subscribers (+42/july).
(See also Alexej's report : https://github.com/bisq-network/roles/issues/25#issuecomment-416579800)
To give a comparison, r/localbitcoins has 2.100 subscribers.
Exchanges subreddits seems a bit different from altcoins subreddits.

I post the Bisq offer book + the bisq F2F offer book from monday to saturday. The offer book is then cross-posted (+customized) to ~4 other subreddits (average this month), which I try to rotate on a 5 days basis (monday-friday). Apart from exposing daily Bisq's currencies/altcoins, this is an opportunity to post links and to show how Bisq is well alive. 
Views for the offer book are in the [100, 200] range. Sometimes more. (Maybe also bots here ?)

In fact, r/bisq is (imo) necessary (one cannot not have a (living) subreddit), but a great part of the effective advertising is done :
- by advertising on other subreddits,
- not by direct posting, but by searching and answering posts and comments.

You have to promote on the place(s) and in the pertinent threads the customer reads. (This needs searching).

On 2018/8/30, the account I use is subscribed to 56 subreddits (a bit too much). Roughly one half are subreddits from altcoins offered/traded on Bisq. The other half are more general subreddits (crypto, btc, etc).

Navigation is a bit delicate (you post on others groups). I take great care of not being classified as a spammer. Negative returns are < 1%. Much more thanks and upvotes than negative returns. Several people wrote that they will try Bisq (and some did) 

For august :
- 200 posts/crossposts
- 70 comments
- details here : https://www.reddit.com/user/Dieter_von_Bisq

It's the comments that bring users. But the posts are also needed to generate comments, and then answer to comments.

Since 14/8, I follow also the news in the DEX/crypto/privacy/etc domains in order :
- to crosspost some general news which may concern/interest Bisq users in r/bisq. This in order to have r/bisq not strictly centered 100% on Bisq.
- to search for opportunities to advertise Bisq

August 2018 was a bit of a special month for Bisq. Bisq had very good (at least its best) numbers with XMR (and in general). I considered this as an opportunity to promote Bisq with numbers not being too small (even there were some naysayers answering "pathetic").

I profit to mention also this post from MK : https://github.com/bisq-network/growth/issues/10. I falled on this post only recently (by chance), but this post describes exactly a part of what I did on reddit this month.

This month report is a bit long, because it's the 1st month for this activity and I wanted to write things to not forget them. Next report(s) should be shorter.

### Nextly
I'll probably increase the daily xposts in september (5/day).

Very certainly, there is still room to exploit reddit.
I'm worried that Bisq has not another good altcoin performer like XMR.
- I think reddit is a good place to push for altcoins, but some strategy is needed. All ideas are welcome.
- I would like also to push on some pertinent national currencies (Venezuela, Turkey, Brazil, etc) but I haven't find a proper angle yet. (I see eg that DASH pushes on Venezuela). There's still to dig.
- I should also push on special points on concerned subreddit. eg promoting the API. Not all market places offer a well-made API.

Annex
-----
- atm, the offer book post is mainly handmade. But I'm coding a python script which will allow to post it in markdown format (as for the F2F offer book). If it's possible to automate things, I'll do it.
- To post on reddit, you have to wait 10 minutes between posts, which makes the process a bit tedious.
- reddit's search engine unfortunately returns only results for the titles.
- I suspect that the number of subscribers for some subreddits is fake (bots subscription).
(subreddit r/pivx with 8K subscribers has eg 300 views for a post, while r/LitecoinMarkets with 30K subscribers has 9 views for the same post.)

**Comment by arunasurya** [comment]
I would like to take on the ambassador role but I prefer to spread the word more in the physical world rather than online. I would be happy to set up and lead local Bisq meetup events, recruit contributors and allies in person in different countries (e.g., by presenting at tech universities, etc), give interviews (once I have a more solid understanding of Bisq and Bisq DAO), present in conferences, set up interviews with leading, trustworthy experts in the bitcoin sphere, and in general focus on building a community, etc. 

Of course, I want to have an online presence but in the form of doing interviews, making educational videos and writing about Bisq, all of which take time and effort. I am not so good at continuous online presence with rapid responses, getting the latest tech news and reacting to it, or providing technical answers. I would also be happy to work with other people who have those skills as a team to bring our strengths together and work in a coordinated fashion.

**Comment by ManfredKarrer** [comment]
@arunasurya Great to hear that! We can definitely need more help in all those areas!!!

**Comment by ghost** [comment]
# 2018-09 Report - Reddit

**This report concerns only the 1st half of september**

There was a copious discussion this month (beginning on sept 13th) about this role on reddit : https://github.com/bisq-network/compensation/issues/115
[Many/all arguments (and fresh numbers) pros and cons for being on reddit can be find there.]
This discussion itself followed a discord vote concerning my compensation request for august.

Given the vote + the discussion, I feel it better to stop with reddit. I thus stopped with this role on sept 18 th.

### Numbers for september 1st half

- 75 posts (22 posts + 53 crossposts)
- 29 comments/answers
- 25 subreddits concerned
- There is no synthetic count of the views, but the views for the last Bisq Offer Book was 280 views on our small r/bisq, 770 views on r/algotrading and 2800 views on r/xmrtrader.
- https://www.reddit.com/user/Dieter_von_Bisq

The posting scheme, the numbers and the trend were roughly in line and continuation with august.

**Comment by goo-technology** [comment]
I can take the embassador role in México (and other latin american countries if needed), make meet-ups and conferences, making online presence at social networks and mantain relations with other crypto, blockchain and traders communities in México.

Juan Sebastian Téllez I.

**Comment by Mycelial1** [comment]
https://github.com/bisq-network/compensation/issues/280

I played a small ambassador role by submitting a superchat in [this video](https://www.youtube.com/watch?v=Fsgi5GZSb_Y&feature=youtu.be) at 36:20 to correct someone on the subject of Bisq and KYC.

The youtuber consistently reads superchats out loud so I thought it a good moment to educate people about Bisq.

I use the same name on Youtube as I do on Slack (@Cfair/DJCfair) 

The video has received 880 views as of today (5/6/2019)

**Comment by doitsu232** [comment]
i am one of the german translators for BISQ but also active as a meetup organizer.
currently i am in vietnam and could do some work here.
i am also a "legendary" member on bitcointalk and have a fair amount of influence there and spend time there regularly as well. anything related to building a following or being an "ambassador" sounds right to me if it fits my activities. i like BISQ and would be available.

**Comment by cbeams** [comment]
Closing as superseded by the new Community Manager role at #95. I believe this is in alignment with @m52go's intentions as @bisq-network/growth team lead.
