### ISSUE TITLE
Growth Maintainer

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#42]
Team: @bisq-network/growth-maintainers
Primary owner: @m52go 
Secondary owner: @ripcurlx 

Spec: https://github.com/bisq-network/roles/blob/master/growth-maintainer.adoc

**Comment by cbeams** [comment]
@ripcurlx, this is all yours now. Please own the new role spec at https://github.com/bisq-network/roles/blob/master/growth-maintainer.adoc (it's little more than a placeholder now, but fine for a start). As mentioned there, please do monthly updates as comments here, as we've been doing for other roles. Thanks.

**Comment by ripcurlx** [comment]
## Report for December
Definition of Bisq [growth process](https://github.com/bisq-network/growth/blob/master/README.adoc) and [meeting structure](https://github.com/bisq-network/growth/blob/master/docs/growth-meeting.md). Moderation and organisation of first three growth calls and support for our first growth experiments. General moderation of `#growthhacking` channel (https://bisq.network/slack-invite).

### Growth Meetings
[1] https://github.com/bisq-network/growth/issues/5
[2] https://github.com/bisq-network/growth/issues/16
[3] https://github.com/bisq-network/growth/issues/20

### Growth Experiments
[4] https://github.com/bisq-network/growth/issues/12
[5] https://github.com/bisq-network/growth/issues/17

**Comment by ripcurlx** [comment]
## Report for January
Moderation and organisation of the first two growth calls this year. Testing and setup for our first YouTube livestreaming.  General moderation of `#growth` channel (https://bisq.network/slack-invite).

### Growth Meetings
[1] https://github.com/bisq-network/growth/issues/33
[2] https://github.com/bisq-network/growth/issues/22

**Comment by ripcurlx** [comment]
## Report for February
Moderation and organizing of four growth calls, two Q&A's and support of our first live trading demo kicking of the BTC/USD liquidity week this month. General moderation of `#growth` channel (https://bisq.network/slack-invite).

### Growth Calls
[1] https://github.com/bisq-network/growth/issues/35
[2] https://github.com/bisq-network/growth/issues/37
[3] https://github.com/bisq-network/growth/issues/38
[4] https://github.com/bisq-network/growth/issues/39

### Q & A's
[1] https://youtu.be/sO5NZomcrCE
[2] https://youtu.be/sARUpDlV3s8

### Special Events
[1] https://www.youtube.com/watch?v=PDRtJGMTl1c

**Comment by ripcurlx** [comment]
## Report for March
Moderation and organizing of five growth calls. General moderation of `#growth` channel (https://bisq.network/slack-invite).

### Growth Calls
[1] https://github.com/bisq-network/growth/issues/40
[2] https://github.com/bisq-network/growth/issues/41
[3] https://github.com/bisq-network/growth/issues/46
[4] https://github.com/bisq-network/growth/issues/47
[5] https://github.com/bisq-network/growth/issues/48

**Comment by ripcurlx** [comment]
## Report for April
Moderation and organizing of five growth calls. General moderation of `#growth` channel (https://bisq.network/slack-invite).

### Growth Calls
[1] https://github.com/bisq-network/growth/issues/50
[2] https://github.com/bisq-network/growth/issues/51
[3] https://github.com/bisq-network/growth/issues/52
[4] https://github.com/bisq-network/growth/issues/53

**Comment by cbeams** [comment]
Feedback:

I'm not sure how valuable it is just to list the growth calls we did. I think the value of a monthly report is also to recap how our growth efforts went over the month. At a high level, what did we do, how did things go? What worked, what didn't? If we grew, why did we grow? What should we focus on in the month to come? I don't mean to suggest you need to write volumes in each of these reports, they can remain as concise as you like, but I'd like to suggest that we try to impart insight where we can. If you were brand new to Bisq, and wanted to help it grow, and all you read was the last few months of the Growth Maintainer's monthly reports, would you walk away with any insight, ideas about how you might be able to help? I don't want these to be mere, perfunctory "TPS reports", but rather an opportunity to share with each other what we're learning and what we think we need over time.

Nits:

 - Please use `2018.04 report` title formatting in the future for consistency with other reports.
 - Please consider back-referencing your compensation request e.g. with "/cc bisq-network/compensation#59". This kind of round-tripping makes everything that much more discoverable / navigable.

**Comment by ripcurlx** [comment]
## 2018.05 report
Moderation and organizing of three growth calls. This month we hold two growth meetings less as I was two weeks offline because I became a dad. General moderation of `#growth` channel (https://bisq.network/slack-invite).

Although it is a little bit of overlap with the [Analytics role](https://github.com/bisq-network/roles/issues/40), I'll provide a quick overview on the network growth and growth activities in May as suggested by @cbeams . 

The main growth activity this month was our [BTC/CAD liquidity week](https://github.com/bisq-network/growth/issues/43). As you can see in following graph the liquidity and trading activity in this market was quite stale over the last couple of months.
<img width="1250" alt="bildschirmfoto 2018-05-30 um 10 40 28" src="https://user-images.githubusercontent.com/170962/40709275-eb8a08ac-63f5-11e8-87a9-c58d4c761a0a.png">
It seems to be that already the announcement of the liquidity week beginning of May helped to spike up the interest in this market. We should check this behavior in our upcoming liquidity weeks as well. During the liquidity week we saw a great increase in number of trades (**+150%**) and in total BTC volume (**+169%**). Although the total volume traded **10,692 USD** (BTC traded in USD) and the total number of trades of **15** is low compared to other markets, it shows that this kind of marketing activity helps to bootstrap certain markets and to attract market makers.

At the moment our growth calls are mainly about liquidity weeks and updates about activities that could influence the growth of the network. As there are so many ways how this can be achieved feel free to add ideas in the [growth repository](https://github.com/bisq-network/growth) and run experiments on your own and get compensated as long as you follow the guideline in our issue template.

/cc https://github.com/bisq-network/compensation/issues/71

**Comment by ripcurlx** [comment]
## 2018.06

Moderation and organizing of four growth calls. Where @flix1 run the last growth call this month and will continue to run it every other week. Thanks for helping out! We also are going to change the format a little bit in the future, not only focusing on reviewing growth experiments, but also have Q&A sessions, external guests,... expect some changes soon 😄

Although we didn't ran any liquidity weeks this months we do see already increased interest in the XMR/BTC market before the upcoming [XMR/BTC liquidity week](https://github.com/bisq-network/growth/issues/60). June was a great month again, gaining **+16% on daily average trading volume** with roughly the same number of daily trades compared to May. So it seems that either people are sticking around and are able/want to trade bigger or it is because of the alt coin trades we saw in the last couple of days.
<img width="1310" alt="bildschirmfoto 2018-06-29 um 15 33 15" src="https://user-images.githubusercontent.com/170962/42095133-0d86d97a-7bb2-11e8-998c-836fd8bf28b2.png">

General moderation of #growth channel (https://bisq.network/slack-invite).

/cc https://github.com/bisq-network/compensation/issues/84

**Comment by ripcurlx** [comment]
# 2018.07
We had three growth calls this month where @flix1 run one of them. Unfortunately our [XMR/BTC](https://github.com/bisq-network/growth/issues/60) and [BTC/CHF](https://github.com/bisq-network/growth/issues/59) liquidity weeks were not as successful as our past ones and didn't show an uplift. This might be the case as we've tried to push our stronger markets in the past where we had already an active local community. We decided to stop for now pushing additional liquidity weeks from our side, but anybody can run a liquidity week for its local market and contact us to support them and to get compensated for it. 

We saw this month less trading activity although the order book is quite full all the time. Since the BTC price started to rise again market active picked up as well and we are seeing a good end of the month trading activtiy.

<img width="1272" alt="bildschirmfoto 2018-07-30 um 12 35 01" src="https://user-images.githubusercontent.com/170962/43392837-2be3ffb4-93f5-11e8-8f2a-e860cada346e.png">

/cc https://github.com/bisq-network/compensation/issues/98

**Comment by ripcurlx** [comment]
## 2018.09
We had three growth calls this month where @ManfredKarrer run one of them. 

@flix1 [September Market Kick-Start Day](https://github.com/bisq-network/growth/issues/67) was a great success and we saw records in total number of trades (104) and offers available (260+).
![bildschirmfoto 2018-09-27 um 10 24 06](https://user-images.githubusercontent.com/170962/46135523-b3ceb300-c245-11e8-94f6-6766793a7e84.png)

All in all it was again a very successful month in terms of volume and offers on the platform. 

We had already five F2F trades and you can find offers for buying and selling crypto on a regular basis.

![bildschirmfoto 2018-09-27 um 11 14 53](https://user-images.githubusercontent.com/170962/46135914-a4039e80-c246-11e8-9fde-146c6e07a57b.png)
![bildschirmfoto 2018-09-27 um 11 10 49](https://user-images.githubusercontent.com/170962/46135915-a49c3500-c246-11e8-8713-56cf011c5ac9.png)

/cc https://github.com/bisq-network/compensation/issues/126

**Comment by ripcurlx** [comment]
## 2018.10
We had three growth calls this month where @flix1 moderated one of them. 

October was a crazy month for the Bisq network. Not only will we see our highest monthly volume ever (**Currently 6.6M USD**) we also had our highest daily peak on 28th of October as well (**110.95 BTC, 710K USD**)
<img width="989" alt="Monthly Volume Reporting" src="https://user-images.githubusercontent.com/170962/47708379-3922fa00-dc2e-11e8-85a4-d4a94a37a685.png">

Although we saw great activitiy in our major markets, this exponential growth was mainly because of the BTC/XMR market. Monero and Bisq have similar values so it is a good match in general, but we don't know exactly why it is spiking right now in that way. Might be that we reached a certain tipping point in offers available (thanks to KYC requirements everywhere) to leverage network effects in a big way. Let's see if this growth will continue next month and if we can push other markets to this point as well.

<img width="1261" alt="Number of trades in all markets" src="https://user-images.githubusercontent.com/170962/47708771-19d89c80-dc2f-11e8-8b5d-878d65b54885.png">

<img width="1258" alt="BTC volume of all markets" src="https://user-images.githubusercontent.com/170962/47708808-32e14d80-dc2f-11e8-9e5b-d04efc571b80.png">


/cc https://github.com/bisq-network/compensation/issues/148

**Comment by ripcurlx** [comment]
## 2018.11 report
Because of my work on the new release I was only able to do two growth calls this month. 

November again is a crazy month for the Bisq network again. We see our highest monthly BTC volume ever (**Currently 1,377.85 BTC**) and total number of trades (**Currently 2,259**).
Total USD volume (**Currently $6.65M**) is a little bit lower than last month, which is mainly because of the current BTC price.
<img width="992" alt="bildschirmfoto 2018-11-30 um 10 46 24" src="https://user-images.githubusercontent.com/170962/49281593-3f0a3600-f48d-11e8-8706-39868c37f5cd.png">

We saw great activitiy in our major markets, but again most of the volume is related to the BTC/XMR market.

/cc https://github.com/bisq-network/compensation/issues/177

**Comment by ripcurlx** [comment]
## 2018.12 report
Because of the holiday season I was only able to do two growth calls this month. 

It sounds very repetitive, but December is a great month for the Bisq network again 🚀. We see our highest monthly BTC volume ever (**Currently 1,524 BTC**) and total number of trades (**Currently 2,401**).
Total USD volume (**Currently $5.6M**) is lower than last month, which is mainly again related to the low BTC price in USD.

<img width="991" alt="bildschirmfoto 2018-12-30 um 12 09 43" src="https://user-images.githubusercontent.com/170962/50546667-d8af3980-0c2b-11e9-8221-63243c7eca4a.png">

This month we have besides the [BTC/XMR market](https://bisq.network/markets/?currency=xmr_btc) a new runner-up with the [BTC/XRC market](https://bisq.network/markets/?currency=xrc_btc). All other markets are showing good activity as well and I'm curious and excited which markets will explode on Bisq next year.

/cc https://github.com/bisq-network/compensation/issues/195

**Comment by ripcurlx** [comment]
## 2019.01 report
We had 5 growth calls this month with the support of @m52go and @eyalron33.

This month we saw a decrease in daily volume (-40%), which is mainly because of reduced trading activity in the last quarter of the month in our strongest markets (XMR and XRC).
![bildschirmfoto 2019-01-30 um 11 40 17](https://user-images.githubusercontent.com/170962/51976184-58773080-2484-11e9-9b71-457aa521c837.png)

On the upside although the volume decreased quite a bit, the number of daily trades is still strong with 75 (-8%). 

![bildschirmfoto 2019-01-30 um 11 42 13](https://user-images.githubusercontent.com/170962/51976076-1c43d000-2484-11e9-9124-aa981dc6b105.png)

So we got more trading activity in new and existing markets where the volume per offer is less. This will help on the long run to get Bisq on a more sustainable path than to simply relay on one or two markets.

/cc https://github.com/bisq-network/compensation/issues/206

**Comment by ripcurlx** [comment]
## 2019.02 report
We had 4 growth calls this month, where @m52go hosted three of them.

This month we saw again a decrease in daily volume (-27%), which is mainly because of reduced trading activity in the Monero market. It just started to pick up again, but this won't change too much of this month's total volume.

![bildschirmfoto 2019-02-27 um 12 16 41](https://user-images.githubusercontent.com/170962/53486688-b5690500-3a89-11e9-9c07-7d4e08d5604d.png)

The number of daily trades decreased to 59 (-21%) and is around the level we had in October last year. 

![bildschirmfoto 2019-02-27 um 12 15 56](https://user-images.githubusercontent.com/170962/53486700-c0239a00-3a89-11e9-9141-2fef45acda47.png)

The total monthly volume will be around 2.2M USD.

/cc https://github.com/bisq-network/compensation/issues/224

**Comment by ripcurlx** [comment]
## 2019.03 report
We had 4 growth calls this month, where @m52go hosted three of them.

Because of the Monero hard fork we saw again a decrease in daily volume (-27%). We had an outstanding day on the 26th with 300k+ USD volume, but the additional volume over the last days of the month won't change too much.

![Bildschirmfoto 2019-03-28 um 17 37 04](https://user-images.githubusercontent.com/170962/55175727-2a5e5600-5180-11e9-9dc9-d1102c77accf.png)

The number of daily trades decreased to 46 (-25%). 

![Bildschirmfoto 2019-03-28 um 17 37 18](https://user-images.githubusercontent.com/170962/55175812-4e219c00-5180-11e9-880b-b6e8ffc01935.png)

The total monthly volume will be around 2M USD.

/cc https://github.com/bisq-network/compensation/issues/247

**Comment by ripcurlx** [comment]
## 2019.04 report
We had 4 growth calls this month, and all of them were hosted by @m52go. Should think about handing over the growth role to @m52go 😄.

It was a special month for Bisq not only because version v1.0.0 was launched including the Bisq DAO. We also saw our second best month in USD trading volume, because of outstanding trading activity in the BTC/XMR market. 

<img width="1306" alt="Bildschirmfoto 2019-04-25 um 10 27 02" src="https://user-images.githubusercontent.com/170962/57138890-1ed00180-6db4-11e9-95de-a7772cf9c3bd.png">

**+303%** in avg. USD volume/day (233k USD),  **+203%** in avg. BTC volume/day (45 BTC) and **+72%** in avg. number of trades/day (70)

<img width="1263" alt="Bildschirmfoto 2019-04-25 um 10 26 41" src="https://user-images.githubusercontent.com/170962/57138892-1ed00180-6db4-11e9-8a32-ef8afe995c8b.png">

Although BSQ is only available on Bisq since 15th of April it already ended as the fourth biggest market on Bisq. In more than 50% of all trades this month BSQ was used to pay the trading fee with (and it was only available in the last two weeks).

So all in all it was an outstanding month for Bisq thanks to all the contributors and traders that support and use Bisq on a daily basis. All the excitement was only shadowed by the activity of a scammer which is now consuming most of our dev resources right now. On the up-side this would have happened sooner or later anyways and if we are able to deliver what is discussed in different proposals right now, we'll also have a scam-proof system soon for fiat payment methods as well.

/cc https://github.com/bisq-network/compensation/issues/269

**Comment by ripcurlx** [comment]
@m52go If you are up for it, I would hand over this role to you and move into a secondary role, as you do besides the reporting (which I missed to do last cycle) all the work already 😄.

**Comment by m52go** [comment]
@ripcurlx yes let's do that. I'll file a report here for June too.

**Comment by m52go** [comment]
## 2019.06 report

We uploaded 3 growth calls to YouTube this month. The fourth one for June 20 was held, but nothing new was shared and no one else attended it, so I didn't upload it.

Activity in the XMR/BTC market was outstanding this month, and it was the key driver for the all-time highs in overall volume across the network.

In terms of BTC, June volume of **2,864.69 BTC was 78.7% higher than the _previous high_ of 1,602.59 BTC from December 2018**, and 180.6% higher than May's volume of 1,020.59 BTC.

Daily volume was correspondingly high at 95.49 BTC, which was also way higher than past figures. 

The average number of trades (94) was strong but not incredible, probably because of the restrictions on fiat trading.

![Screenshot from 2019-07-09 11-30-02](https://user-images.githubusercontent.com/735155/60902173-32c53300-a23d-11e9-8c69-9b9537f0932c.png)

Thanks to @jmaurice [and others](https://github.com/bisq-network/growth/issues/138) the JPY-BTC market got a kickstart in June.

/cc https://github.com/bisq-network/compensation/issues/304

**Comment by bisq-github-admin-3** [comment]
@m52go I just made you the primary growth maintainer (see https://github.com/bisq-network/roles/issues/42#issue-278488780). Thanks for taking this role now officially 😉

**Comment by m52go** [comment]
## 2019.07 report

We uploaded 3 growth calls to YouTube this month. I found out late that I wouldn't be able to host the July 4 one.

June was a blockbuster month, and while this month didn't beat it, it still did quite well—July volume was **1651.09 BTC**.

Daily volume was 53.26 BTC. With the exception of June, that's the highest we've ever seen.

![Screenshot from 2019-08-07 11-55-57](https://user-images.githubusercontent.com/735155/62637867-59dd5600-b90a-11e9-9c80-4c80638b2283.png)

Would love to give another shout-out to jmaurice and tdhr. tdhr made an incredible talk at the Tokyo Bitcoin Hackers meetup, where he not only covered Bisq but somehow managed to cover the DAO too in a way that impressed a lot of people.

This month also saw the creation of a number of community-run Twitter accounts for countries including Japan, France, Portugal, and Spain.

/cc https://github.com/bisq-network/compensation/issues/323

**Comment by m52go** [comment]
## 2019.08 report

### Growth Calls

August marked the beginning of a new format for growth calls which I dubbed the Bisq BRIEF series. These calls are themed and occur every other week. The goals are to be (1) interesting discussions with the community in order to get (2) wider engagement so that Bisq can better communicate with the user base and attract more contributors.

Two calls were held, one on the Bisq DAO through the first 4 months, and another on contributing to Bisq. These calls were amazingly well-attended, given the attendance of our previous calls, with ~30 people attending each one and a few dozen watching afterward on YouTube.

The follow-up afterward further magnified the message for those who couldn't attend.

**Exhibit A**

![Screenshot from 2019-09-09 13-27-31](https://user-images.githubusercontent.com/735155/64552706-c8e10c80-d305-11e9-9d1d-0313e6165db4.png)

**Exhibit B**

![Screenshot from 2019-09-09 13-26-46](https://user-images.githubusercontent.com/735155/64552712-cc749380-d305-11e9-9f84-9e0e6682e0bf.png)

### Volume

August was another solid month, setting 2 new all-time records: number of trades was 3 306 and average number of daily trades was 98.

Fiat volume was 50.21 BTC while altcoin volume was 2404.24 BTC for a total of 2454.45 BTC for the month.

![Screenshot from 2019-09-09 13-36-11](https://user-images.githubusercontent.com/735155/64553433-58d38600-d307-11e9-84d7-15d59114e340.png)

/cc https://github.com/bisq-network/compensation/issues/361

**Comment by m52go** [comment]
## 2019.09 report

### Growth Calls

New call format continues to go well.

Two calls were held, one about strategies for bootstrapping new markets, and another to explore new social channels.

### Volume

September saw a drop in Monero trading, which resulted in a depressed BSQ market. But fiat trading was still relatively solid in spite of trading limits at 45.8 BTC for the month. In historical terms, overall numbers were still quite strong—there were 2 415 total trades at an average of 81 per day (third highest ever).

The high number of trades shows interest in Bisq remains strong...just that trade sizes aren't very big at the moment. Hopefully that changes soon as fiat buying limits are lifted soon with v1.2. And the Monero market has always fluctuated wildly, so there's no surprise there.

Fiat volume was 45.8 BTC while altcoin volume was 1091.33 for a total of 1137.13 BTC for the month (more details [here](https://bisq.network/stats/) and [here](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA)).

### Intentional Efforts

Intentional established market efforts remain on hold until fiat trading limits are lifted with v1.2.

wiz continues to grind in Japan (and globally) with IRL events, a new payment method, a Keybase group, and a flurry of bang-on Bisq tweets.

FKrauss is working on translations and payment methods for Brazil, but even now, BTC-BRL is a top-5 trading pair by closed trades and a top-3 trading pair by open offers.

/cc https://github.com/bisq-network/compensation/issues/372

**Comment by m52go** [comment]
## 2019.10 report

October was pretty quiet in anticipation of the v1.2 release to lift 0.01 BTC trading limits. I did not hold any growth events.

### Volume

The story for October was much the same as it was for September: major drop in Monero trading, but strong fiat trading. This is reflected in trade volume and trade frequency: total BTC volume traded went down by over 50%, but number of trades decreased only 10% to 2 288.

Fiat volume was 54.16 BTC while altcoin volume was 449.35 BTC for a total of 503.57 BTC for the month (more details [here](https://bisq.network/stats/) and [here](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA)).

Growth efforts will begin again soon now that v1.2 is out. Bi-weekly growth calls are already scheduled to begin again this week.
 
/cc https://github.com/bisq-network/compensation/issues/408

**Comment by m52go** [comment]
## 2019.11 report

November was another down month for volume, but growth initiatives are picking up.

wiz and I have now appeared on a couple of major podcasts, and we expect to do more now that v1.2 is out (will proactively reach out in the new year). 

FKrauss started [a spreadsheet](https://docs.google.com/spreadsheets/d/1RZr5Fna98lTrNAEzlwxANT2_Hn5p9N0W9pIK7_gPAAM/edit#gid=1215057867) to determine high-priority events Bisq should have a presence at in advance to allow time for getting speaking slots and finding the right contributors to attend.

Newer contributors are planning initiatives in Mexico and Latin America (events, podcasts, meetups).

I held 2 growth-oriented calls this month, one for the Bisq v1.2 release, and the other for kick-starting the new support initiative.

### Volume

The story for November was nothing to write home about. As before, fiat volume has stayed strong despite another drop in altcoin volume (although both dropped).

Fiat volume was 47.60 BTC while altcoin volume was 417.84 BTC for a total of 465.44 BTC for the month (more details [here](https://bisq.network/stats/) and [here](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA)).
 
/cc https://github.com/bisq-network/compensation/issues/442

**Comment by m52go** [comment]
## 2019.12 Report

Growth remains bad, to the point BSQ is suffering an economic spiral. We are [finalizing growth strategies](https://github.com/bisq-network/growth/issues/179) right now and are implementing ASAP.

Short-term plans involve putting on liquidity events for key markets. Mid-term plans involve better understanding Bisq usage dynamics to make growth efforts more reliable and repeatable. Longer-term efforts involve implementing a full growth funnel including a smarter content strategy, social, site optimization, and in-program elements to drive volume in a more holistic process-oriented way.
 
/cc https://github.com/bisq-network/compensation/issues/471

**Comment by m52go** [comment]
## 2020.01 Report

Overall bitcoin volume in January was lower than we've seen in a while, but number of trades was higher than we've seen in a while -- fiat trade volume (which are typically smaller than altcoin trades) was strong, although it's not clear users are taking advantage of account signing.

For example, here's a distribution of USD trades in January by size:

![Screenshot from 2020-02-15 09-45-48](https://user-images.githubusercontent.com/735155/74589949-e4151e00-5001-11ea-8694-5598d99020dd.png)
 
/cc https://github.com/bisq-network/compensation/issues/497

**Comment by m52go** [comment]
## Cycle 11 Report

Overall trading activity in February was strong -- there were 2903 trades on the network, the second-highest ever. 

Fiat trades in particular continue their consistent upward trajectory:

![Screenshot from 2020-03-16 09-36-30](https://user-images.githubusercontent.com/735155/76763952-efd43b80-678b-11ea-890f-a17efb1d6c18.png)

Hence [the upcoming focus on payment methods](https://github.com/bisq-network/roles/issues/38#issuecomment-599561611) to increase fiat trade size. We know this is the core of Bisq's mission, and where it excels. Historically trade size seems heavily influenced by market price (e.g., during 2017 hype cycle, mean and median trade sizes were hovering in the 1000 USD range, but then dropped to about 400 USD). Right now, especially in the USD market, trades are much smaller on average than at any point in the past.

From a markets perspective, it seems that XMR, JPY, and L-BTC have the highest chances of boosting volume with higher-size trades. It remains to be figured out what actually drives those markets in order to get more consistent activity from them.

In March we launched a [significant initiative](https://github.com/bisq-network/projects/issues/14) to boost volume on the network.
 
/cc https://github.com/bisq-network/compensation/issues/513

**Comment by cbeams** [comment]
@m52go, I'm in the process of creating roles for each of the team leads. It seems to me this role issue should probably be superseded by or possibly renamed to Growth Team Lead. What do you think? I'll hold off on creating that issue until you weigh in.

**Comment by cbeams** [comment]
>  I'll hold off on creating that issue until you weigh in.

Scratch that, I just created https://github.com/bisq-network/roles/issues/100 for consistency with the other similar issues being created. We can continue with this one and close that one, or we can close this one as superseded by that one. I'm inclined to do the latter, just to have a fresh start there and be on the same footing with the other team lead issues.

**Comment by m52go** [comment]
@cbeams sure, no strong feelings about keeping this role. Might as well go for consistency with other team lead roles. Closing now.
