### ISSUE TITLE
Seednode Maintainer

### ISSUE THREAD

**Issue by cbeams** [bisq-network/roles#6]
Docs:
Team: @bisq-network/seednode-maintainers 
Primary owner: @freimair  
Secondary owner: @wiz

**Comment by ManfredKarrer** [comment]
## 2018.04 report
There have been some bigger refactoring of the startup process which also affected the seed node.

**Comment by ManfredKarrer** [comment]
## 2018.05 report
Nothing to report

**Comment by ManfredKarrer** [comment]
## 2018.06 report

The have been some code changes related to the startup code refactoring.

**Comment by ManfredKarrer** [comment]
## 2018.07 report

Nothing to report.

/cc bisq-network/compensation#93

**Comment by ManfredKarrer** [comment]
## 2018.08 report

Nothing to report.

/cc bisq-network/compensation#112

**Comment by ManfredKarrer** [comment]
## 2018.09 report

Nothing to report.

/cc bisq-network/compensation#125

**Comment by ManfredKarrer** [comment]
## 2018.11 report

Nothing to report.

/cc bisq-network/compensation#180

**Comment by ManfredKarrer** [comment]
## 2019.01 report

Nothing to report.

/cc bisq-network/compensation#205

**Comment by ManfredKarrer** [comment]
## 2019.02 report

Nothing to report.

@freimair Could you take over primary role for that as it is very related to the network work.

/cc bisq-network/compensation#227

**Comment by freimair** [comment]
# 2019.03 report
- ongoing survey of memory requirements optimizations
- ongoing survey on syncing seednodes periodically

**Comment by wiz** [comment]
## Cycle 6 report

I tookover the secondary maintainer role from @ManfredKarrer last month. Things are mostly stable now, so not much to report. Recently I've been testing some new code to improve stability of seednodes, but unfortunately there were issues so we had to revert it. We aim to eliminate the seednode branch entirely within the next few months.

/cc https://github.com/bisq-network/compensation/issues/380

**Comment by wiz** [comment]
## Cycle 7 report

We had some major issues with seednodes last week due to a bug in Bisq that caused lots of P2P traffic. We could use some additional capacity in terms of number of seednodes and number of max connections, so I'm planning to have all seednode operators setup a 3rd instance.

Also I setup a new server to takeover the ef5qnzx6znifo3df.onion seednode from @Emzy, which will be migrated in the next few days.

/cc [bisq-network/compensation#398](https://github.com/bisq-network/compensation/issues/398)

**Comment by wiz** [comment]
## Cycle 8 report

The seednodes have been decently stable recently. We completed the migration of ef5qnzx6znifo3df.onion to a new Dell server running FreeBSD, which was a huge accomplishment getting Bisq to run on FreeBSD. Other than that, not much to report.

/cc https://github.com/bisq-network/compensation/issues/448

**Comment by wiz** [comment]
## Cycle 9 report

All seednodes have been upgraded to v1.2.5. Some nodes occasionally experience crash and OOM issues, need to investigate. As an experiment two of my seednodes are running a new Tor configuration, and one of them is running a 8 hour restart instead of the standard 24 hour restart, which seems to help stability.

/cc https://github.com/bisq-network/compensation/issues/470

**Comment by cbeams** [comment]
Closing as not needed. Seednode _maintenance_ is handled by the @bisq-network/bisq-maintainers, as the seednode is (now once again) part of the main Bisq repository. Seednode _operation_ is handled by #15.
