### ISSUE TITLE
Keybase Admin

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/roles#79]
Owners and Admins of the public `bisq` Keybase team at https://keybase.io/team/bisq

Docs: https://bisq.wiki/Keybase
Team: @bisq-network/keybase-admins

**Comment by ManfredKarrer** [comment]
@m52go Is it OK if I assign you for now. Once we migrate we need to check out who will actually take the role....

**Comment by wiz** [comment]
@m52go since this was never implemented and we're on keybase now how about we close this role

**Comment by cbeams** [comment]
Closing as dropped. I believe nothing ever happened with Rocket Chat and Keybase has become our chat hub in the meantime.

**Comment by m52go** [comment]
@cbeams @wiz sorry for missing your comments earlier—this role was kept open because it's the one hard-coded in the DAO. When people post bonds for Keybase Admin, they'll need to post them for this GitHub role. Would be great if this were changed, but that's the way it is right now.

https://github.com/bisq-network/bisq/blob/d4e566f6e7b49ea2a9b1f7f2ead1940ba165b769/core/src/main/java/bisq/core/dao/state/model/governance/BondedRoleType.java#L47

**Comment by wiz** [comment]
okay so close the keybase issue and rename this one to keybase and change the strings in the app to say keybase instead of rocket chat

**Comment by cbeams** [comment]
Per @wiz's plan at https://github.com/bisq-network/roles/issues/79#issuecomment-618483481:

- [x] close the keybase issue (see https://github.com/bisq-network/roles/issues/60#issuecomment-623303560)
- [x] rename this one to keybase
- [x] change the strings in the app to say keybase instead of rocket chat (see https://github.com/bisq-network/bisq/pull/4232)

**Comment by m52go** [comment]
## Cycle 13 Report

Nothing particularly notable to report, aside from an overzealous altcoiner who added a lot of Bisq people to their own Keybase team. Keybase the company was acquired.

/cc https://github.com/bisq-network/compensation/issues/572

**Comment by cbeams** [comment]
## Cycle 13 report

I have proposed to post bond as the Keybase team owner in https://github.com/bisq-network/proposals/issues/223. Nothing else to report.

/cc bisq-network/compensation#573

**Comment by cbeams** [comment]
## Cycle 14 report

A proposal has been submitted at bisq-network/proposals#232 for @kbteamowner to take over this role from me. I will continue to own the role until their proposal is approved and their bond is posted. At that time, I'll hand over ownership of the Keybase team to them and remove the owner role from my user. Assuming everything goes to plan, this will be my last cycle report, and @kbteamowner will report here going forward.

/cc bisq-network/compensation#600

**Comment by cbeams** [comment]
Per https://github.com/bisq-network/proposals/issues/232#issuecomment-659511954, I have just made @kbteamowner the owner of the Bisq keybase team. For some reason, though, I am unable to assign them to this issue. I have removed myself as an assignee in any case.

**Comment by cbeams** [comment]
## Cycle 15 report

As mentioned above, this role has been handed off to @kbteamowner, and this will be my final cycle report. Note that I have successfully removed myself from this issue now (I was unable to do so before, as mentioned above). I have also removed myself from the @bisq-network/keybase-admins team and granted @kbteamowner the Maintainer role there.

/cc bisq-network/compensation#612
