### ISSUE TITLE
Mediator

### ISSUE THREAD

**Issue by bisquser** [bisq-network/roles#87]
I am very familiar with Bisq and the trading process and customer support and would like to become a mediator. My rate is initially 50 BSQ/mediation case. After the first month we can discuss again if that rate is realistic for the effort. I will also do the bonding of 10 000 BSQ.

**Comment by leo816** [comment]
I would like to become a mediator (mediation support is in development). I am very familiar with Bisq and the arbitration process and I am aware of the duties involved in that role and willing to set up the 10000 BSQ bond for mediators.
As mediators are not paid in BTC from trading fees like arbitrators I will deliver a monthly report about the number of cases and based on that number request BSQ for that role.
My rate is 50 BSQ/mediation case.

thank you.

**Comment by m52go** [comment]
@bisquser @leo816 this repository is intended for monthly updates for **approved** roles. 

It is acceptable that this issue was created as a placeholder, but since your roles have not been  approved by DAO voting yet, please direct proposal-related activity to the [proposal repository](https://github.com/bisq-network/proposals).

**Comment by m52go** [comment]
On second thought, I don't think it would be prudent to have a role issue owned by a role owner who's not an admin or maintainer of this repository. I'm closing this and will re-open a new issue shortly.
